# Generated by Django 5.2.1 on 2025-07-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_alter_certifications_level_of_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('posted_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Career Opportunities',
                'db_table': 'career_opportunities',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.AlterField(
            model_name='certifications',
            name='level_of_difficulty',
            field=models.CharField(choices=[('0', 'easy'), ('1', 'medium'), ('2', 'hard'), ('3', 'extreme'), ('4', 'impossible')], default='0', max_length=20),
        ),
    ]
